In [13]:
import numpy as np

In [14]:
y_true = np.array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0])

In [15]:
y_pred = np.array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0])

In [16]:
y_true == 1

array([ True, False,  True,  True, False,  True, False, False,  True,
       False])

In [17]:
y_pred==1

array([ True, False,  True, False, False,  True,  True, False, False,
       False])

In [23]:
TP=np.sum((y_true==1)&(y_pred==1))
print(f"True positives = {TP}")

True positives = 3


In [29]:
TN=np.sum((y_true==0)&(y_pred==0))
print(f"True negatives = {TN}")

True negatives = 4


In [28]:
FP=np.sum((y_true==0)&(y_pred==1))
print(f"False positives = {FP}")

False positives = 1


In [30]:
FN = np.sum((y_true == 1) & (y_pred == 0))
print(f"False negatives = {FN}")


False negatives = 2


In [31]:
correct_predictions = TP + TN
total_predictions = TP + TN + FP + FN

In [32]:
accuracy = correct_predictions / total_predictions
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.70


In [34]:
positivea_predictions=TP+FP
precision=TP/positivea_predictions if positivea_predictions !=0 else 0
print(f"precision: {precision:.2f}")

precision: 0.75


In [35]:
actual_positives = TP + FN  
recall = TP / actual_positives if actual_positives != 0 else 0

print(f"Recall: {recall:.2f}")

Recall: 0.60


In [36]:
precision_recall_sum = precision + recall
f1_score = 2 * (precision * recall) / precision_recall_sum if precision_recall_sum != 0 else 0

print(f"F1 Score: {f1_score:.2f}")

F1 Score: 0.67


In [37]:
y_prob = np.array([0.9, 0.1, 0.8, 0.3])

In [40]:
y_bool =( y_prob >= 0.5)
print(y_bool)

[ True False  True False]


In [43]:
yy_predicted=y_bool.astype(int)
print(yy_predicted)

[1 0 1 0]


In [44]:
a=yy_predicted.reshape(1,4)
print(a)

[[1 0 1 0]]
