In [23]:
import numpy as np
import pandas as pd

In [24]:
df=pd.read_csv("health_lifestyle_data_large.csv")

In [25]:
df

Age   BMI  Exercise_Hours  Sleep_Hours  Blood_Pressure  Glucose_Level  \
0     56  20.6             3.2          8.5             149             86   
1     69  27.8             1.1          5.7             141             88   
2     46  24.0             1.7          6.0             129             80   
3     32  21.3             2.4          7.4             137            105   
4     60  24.4             0.1          6.1             142            117   
..   ...   ...             ...          ...             ...            ...   
995   60  28.7             3.0          4.4             139             84   
996   64  23.5             0.2          7.7             148            189   
997   62  25.3             2.2          7.9             129            169   
998   35  29.9             0.9          6.2             133            140   
999   55  25.5             3.2          3.9             132            164   

     Income  Diabetic_Score  
0     23052            16.9  
1     64377            18.2  
2     87838            14.8  
3     87819            18.0  
4     35620            20.3  
..      ...             ...  
995   66936            22.3  
996   28593            27.6  
997   37358            25.6  
998   57381            25.4  
999   48074            27.6  

[1000 rows x 8 columns]

In [26]:
df.head()

Age   BMI  Exercise_Hours  Sleep_Hours  Blood_Pressure  Glucose_Level  \
0   56  20.6             3.2          8.5             149             86   
1   69  27.8             1.1          5.7             141             88   
2   46  24.0             1.7          6.0             129             80   
3   32  21.3             2.4          7.4             137            105   
4   60  24.4             0.1          6.1             142            117   

   Income  Diabetic_Score  
0   23052            16.9  
1   64377            18.2  
2   87838            14.8  
3   87819            18.0  
4   35620            20.3

In [27]:
df.describe()

Age          BMI  Exercise_Hours  Sleep_Hours  Blood_Pressure  \
count  1000.00000  1000.000000     1000.000000   1000.00000     1000.000000   
mean     43.81900    27.230700        1.544500      6.50000      134.208000   
std      14.99103     3.953332        0.919846      1.01587       14.186049   
min      18.00000    15.400000        0.000000      3.50000      110.000000   
25%      31.00000    24.575000        0.900000      5.80000      123.000000   
50%      44.00000    27.200000        1.500000      6.50000      133.000000   
75%      56.00000    29.725000        2.200000      7.20000      146.000000   
max      69.00000    37.500000        4.000000      9.00000      159.000000   

       Glucose_Level        Income  Diabetic_Score  
count    1000.000000   1000.000000     1000.000000  
mean      139.741000  59527.618000       22.858900  
std        33.642082  23305.433964        4.106578  
min        80.000000  20028.000000       11.500000  
25%       112.000000  39642.500000       19.800000  
50%       140.000000  58534.500000       22.750000  
75%       168.000000  79494.000000       26.000000  
max       199.000000  99971.000000       33.800000

In [28]:
df.isnull().sum()

Age               0
BMI               0
Exercise_Hours    0
Sleep_Hours       0
Blood_Pressure    0
Glucose_Level     0
Income            0
Diabetic_Score    0
dtype: int64

In [29]:
np_array=df[['Age','BMI']].values

In [30]:
np_array

array([[56. , 20.6],
       [69. , 27.8],
       [46. , 24. ],
       ...,
       [62. , 25.3],
       [35. , 29.9],
       [55. , 25.5]], shape=(1000, 2))

In [31]:
np_array.shape

(1000, 2)

In [32]:
random=np.random.randint(-2,6,size=(2,3))

In [33]:
random

array([[ 4,  3,  0],
       [ 5, -2, -1]])

In [34]:
dot=np_array@random

In [36]:
another_way=np_array.dot(random)

In [37]:
print(dot)

[[327.  126.8 -20.6]
 [415.  151.4 -27.8]
 [304.   90.  -24. ]
 ...
 [374.5 135.4 -25.3]
 [289.5  45.2 -29.9]
 [347.5 114.  -25.5]]


In [38]:
print(another_way)

[[327.  126.8 -20.6]
 [415.  151.4 -27.8]
 [304.   90.  -24. ]
 ...
 [374.5 135.4 -25.3]
 [289.5  45.2 -29.9]
 [347.5 114.  -25.5]]
