In [ ]:
import pandas as pd

In [1]:
import numpy as np
import random

In [4]:
a=np.random.randint(-30,40, size=(10, 10))

In [21]:
print(a)

[[ -3 -18  -8  32 -10 -22  17  38 -24 -23]
 [-17  21  18  -9 -30   5  18   5   4  -8]
 [ 10 -10  15  21  16   2 -16 -29  18   6]
 [ 16  33 -24  26  24  13  31  -8  30  -9]
 [ -7   0 -27 -13   7 -21  -1  19  -5 -21]
 [-26  -7  -4  24  10 -18  39  21 -13   8]
 [  9 -18 -15  34 -11 -13   7 -18  -4  35]
 [ 24  -9  25 -23  -9  13   4   2  21  13]
 [ 14   1  -1  12  12  34  33  25  37  16]
 [-22 -20 -25   7 -12  10  22  11  19 -13]]


In [18]:
b=np.random.randint(-70,40, size=(10, 8))  

In [22]:
print(b)


[[-52   1 -30   9 -40 -32 -23 -45]
 [-37 -47   0 -24 -25 -38   8  -4]
 [ 32 -20 -47  31  15 -28   3 -62]
 [ 37  13  35 -29 -17 -67 -38 -21]
 [-70 -65 -41 -34 -14 -26  11   7]
 [  9 -19  21 -62 -38  30  -1  37]
 [-26  36 -34 -37   6 -35  29 -54]
 [-36 -69   7 -61 -51 -12  -3  22]
 [-38  -8  13 -25 -44 -43  24 -58]
 [-48 -18 -49 -23 -28 -69  34  30]]


In [23]:
c=np.dot(a,b)

In [24]:
print(c)

[[ 2458  1083  2037  -885   746    28 -2382  -233]
 [ 2079   789   551   -15   709   465   951 -1605]
 [  493   548  -603  1291  -159 -2403  -630 -2233]
 [-4648  -934   568 -4970 -3571 -4728   424 -3121]
 [-1120  -621  1427    27   629  2510  -248  1666]
 [ -151   302  -720 -2693   802 -2808   774  -304]
 [  567  3455  -328   376    91 -3838  -445  -167]
 [-1817  -410 -2544   280 -1703  -925  1269 -2693]
 [-4819 -2404  -981 -6832 -5417 -4704  1639 -2380]
 [ 1207  2214  2995 -2569  -227  1485   482   321]]


In [25]:
np.matrix_transpose(c)

array([[ 2458,  2079,   493, -4648, -1120,  -151,   567, -1817, -4819,
         1207],
       [ 1083,   789,   548,  -934,  -621,   302,  3455,  -410, -2404,
         2214],
       [ 2037,   551,  -603,   568,  1427,  -720,  -328, -2544,  -981,
         2995],
       [ -885,   -15,  1291, -4970,    27, -2693,   376,   280, -6832,
        -2569],
       [  746,   709,  -159, -3571,   629,   802,    91, -1703, -5417,
         -227],
       [   28,   465, -2403, -4728,  2510, -2808, -3838,  -925, -4704,
         1485],
       [-2382,   951,  -630,   424,  -248,   774,  -445,  1269,  1639,
          482],
       [ -233, -1605, -2233, -3121,  1666,  -304,  -167, -2693, -2380,
          321]])

In [26]:
pip list

Package                   Version
------------------------- --------------
anyio                     4.9.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.5
attrs                     25.3.0
babel                     2.17.0
beautifulsoup4            4.13.4
bleach                    6.2.0
certifi                   2025.4.26
cffi                      1.17.1
charset-normalizer        3.4.2
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.3.2
cycler                    0.12.1
debugpy                   1.8.14
decorator                 5.2.1
defusedxml                0.7.1
executing                 2.2.0
fastjsonschema            2.21.1
filelock                  3.13.1
fonttools                 4.58.1
fqdn                      1.5.1
fsspec                    2024.6.1
gitdb                     4.0.12
GitPython                 3.1.44
h11      

In [27]:
x=np.random.randint(-30,40, size=(3, 3))

In [28]:
print(x)

[[  7  25  23]
 [-19   7  38]
 [-26 -10 -30]]


In [29]:
y=np.random.randint(-80,40, size=(3, 3))

In [31]:
print(y)

[[-73 -19   4]
 [-30 -67  36]
 [ -9 -76 -66]]


In [32]:
np.dot(x,y)

array([[-1468, -3556,  -590],
       [  835, -2996, -2332],
       [ 2468,  3444,  1516]])

In [34]:
np.transpose(y)

array([[-73, -30,  -9],
       [-19, -67, -76],
       [  4,  36, -66]])